# Generated by Django 4.2.5 on 2023-10-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(2, 'Soporte'), (3, 'Usuario')], verbose_name='Rol'),
        ),
    ]
