# Generated by Django 4.2.4 on 2023-09-04 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prioridad',
            old_name='nombre',
            new_name='nombre_prioridad',
        ),
    ]
