# Generated by Django 4.2.4 on 2023-09-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_nombre_prioridad_nombre_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='descripción',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.prioridad', verbose_name='Prioridad'),
        ),
    ]
