# Generated by Django 4.2.4 on 2023-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_descripción_alter_ticket_id_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('pausado', 'Pausado')], default='abierto', max_length=50, verbose_name='Estado'),
        ),
    ]
