# Generated by Django 4.2.5 on 2023-09-20 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoría',
            name='id_subcategoría',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id subcategoría'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_categoría',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.categoría', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_subcategoría',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.subcategoría', verbose_name='Subcategoría'),
        ),
    ]
