# Generated by Django 4.2.5 on 2023-09-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_subcategoría_id_subcategoría_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='documentos_adicionales',
            field=models.FileField(blank=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Abierto'), (2, 'En Progreso'), (3, 'Completado'), (4, 'Pausado')], default=1, verbose_name='Estado'),
        ),
    ]
